data =[
            {
                "id": 9112,
                "group_id": 1,
                "group_name": "业务性能组",
                "feature_text": "线程收敛：周期线程池读取配置错误误收敛fix",
                "is_effected_ad": 0,
                "developer": "万英买",
                "tester": "习星飞",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 1,
                "remark": "",
                "operation_name": "习星飞"
            },
            {
                "id": 9089,
                "group_id": 2,
                "group_name": "商业化组",
                "feature_text": "修复插页五要素的UI异常问题",
                "is_effected_ad": 1,
                "developer": "吴志强",
                "tester": "戴旭峰",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9108,
                "group_id": 2,
                "group_name": "商业化组",
                "feature_text": "橱窗加入广告标识",
                "is_effected_ad": 1,
                "developer": "盛昌",
                "tester": "纪晓菁",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9087,
                "group_id": 3,
                "group_name": "研发三组",
                "feature_text": "开屏入画问题fix",
                "is_effected_ad": 1,
                "developer": "疏礼凡",
                "tester": "纪晓菁",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9088,
                "group_id": 3,
                "group_name": "研发三组",
                "feature_text": "修复音量键翻页默认开",
                "is_effected_ad": 0,
                "developer": "蒋学皓",
                "tester": "赵卫峰",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9090,
                "group_id": 3,
                "group_name": "研发三组",
                "feature_text": "修复终章页继续阅读埋点重复上报",
                "is_effected_ad": 0,
                "developer": "蒋学皓",
                "tester": "赵卫峰",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9094,
                "group_id": 3,
                "group_name": "研发三组",
                "feature_text": "修复字体大小迁移优先UI显示",
                "is_effected_ad": 0,
                "developer": "蒋学皓",
                "tester": "赵卫峰",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9115,
                "group_id": 3,
                "group_name": "研发三组",
                "feature_text": "上下翻页：还原线上底部广告背景色逻辑",
                "is_effected_ad": 0,
                "developer": "蒋学皓",
                "tester": "赵卫峰",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9101,
                "group_id": 4,
                "group_name": "研发二组",
                "feature_text": "\u003c我的页面\u003e 游客变登录用户后，升级弹框显示异常",
                "is_effected_ad": 0,
                "developer": "胡瑞龙",
                "tester": "张保华",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9102,
                "group_id": 4,
                "group_name": "研发二组",
                "feature_text": "收银台文字锯齿",
                "is_effected_ad": 0,
                "developer": "胡瑞龙",
                "tester": "张保华",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9103,
                "group_id": 4,
                "group_name": "研发二组",
                "feature_text": "勋章 flutter更新",
                "is_effected_ad": 0,
                "developer": "胡瑞龙",
                "tester": "张保华",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9114,
                "group_id": 5,
                "group_name": "研发一组",
                "feature_text": "百度tts 模型文件完整性校验",
                "is_effected_ad": 0,
                "developer": "周海民",
                "tester": "张元元",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9092,
                "group_id": 6,
                "group_name": "研发四组",
                "feature_text": "三折叠小窗ui优化调整及新增小窗5s后自动收起逻辑",
                "is_effected_ad": 0,
                "developer": "朱君",
                "tester": "李雪芳",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9096,
                "group_id": 6,
                "group_name": "研发四组",
                "feature_text": "三折叠图书tab卡片ui修复",
                "is_effected_ad": 0,
                "developer": "朱君",
                "tester": "乔俊一",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9098,
                "group_id": 6,
                "group_name": "研发四组",
                "feature_text": "帖子详情、评论详情埋点",
                "is_effected_ad": 0,
                "developer": "尹余",
                "tester": "王敏2",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            },
            {
                "id": 9100,
                "group_id": 6,
                "group_name": "研发四组",
                "feature_text": "去掉发布页滑动隐藏键盘功能",
                "is_effected_ad": 0,
                "developer": "尹余",
                "tester": "王敏2",
                "develop_leader": "",
                "test_leader": "",
                "test_status": 0,
                "remark": "",
                "operation_name": ""
            }
        ]


for i in data:
    # print(i)
    s = i['group_name']+' '+i['feature_text']+' '+i['developer']+' '+i['tester']
    print(s)
